[build]
  command = "yarn install --frozen-lockfile && yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.22"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/live"
  to = "https://sessionize.com/gdg-devfest-2025/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404