[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/live"
  to = "https://sessionize.com/gdg-devfest-2025/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404