[build]
  command = "yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/live"
  to = "https://sessionize.com/gdg-devfest-2025/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[context.production]
  command = "yarn build"

[context.deploy-preview]
  command = "yarn build"

[context.branch-deploy]
  command = "yarn build"